services:
  - type: web
    name: line-bot
    env: python
    plan: free
    build:
      buildCommand: "pip install -r requirements.txt"
      pythonVersion: 3.9.16
    startCommand: "python app.py"
