# ===============================
# GitHub Actions ワークフロー
# Render の cron エンドポイントを定期的に ping する（テスト用）
# ===============================

name: Ping Render Cron Endpoint (Test)  # ワークフロー名

on:
  schedule:
    # GitHub Actions cron は UTC 基準
    # 曜日指定なしで毎日実行
    # JST 22:35 → UTC 13:35
    # 書式: 分 時 日 月 曜日
    - cron: "35 14 * * *"

jobs:
  cron:
    runs-on: ubuntu-latest  # GitHub の Ubuntu 環境で実行
    steps:
      - name: Ping Render cron endpoint
        run: |
          # Render 上で用意した cron 用エンドポイントにアクセス
          TARGET_URL="https://line-bot-1-rsyx.onrender.com/cron"
          
          echo "⏳ Pinging $TARGET_URL ..."
          # タイムアウト 10秒で curl 実行。失敗しても workflow は止まらない
          curl -fsS --max-time 10 "$TARGET_URL" || echo "⚠️ Ping failed"
          
          echo "✅ Ping completed"
