# ===============================
# GitHub Actions ワークフロー
# 毎朝 08:45 JST に Render の /cron を実行し、
# 5分後に再実行する
# ===============================

name: Morning Cron Ping

on:
  schedule:
    # JST 08:45 → UTC 23:45 前日
    # 書式: 分 時 日 月 曜日
    - cron: "45 23 * * *"  # 毎日 JST 08:45

jobs:
  morning-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render /cron endpoint (1回目)
        run: |
          # Render 健康チェック用 URL
          TARGET_URL="https://line-bot-1-rsyx.onrender.com/cron"
          
          echo "⏳ First ping to $TARGET_URL (08:45 JST)..."
          curl -fsS --max-time 10 "$TARGET_URL" || echo "⚠️ First ping failed"

      - name: Wait 5 minutes before second ping
        run: |
          echo "⏳ Waiting 300 seconds (5 minutes) before second ping..."
          sleep 300

      - name: Ping Render /cron endpoint (2回目)
        run: |
          TARGET_URL="https://line-bot-1-rsyx.onrender.com/cron"
          
          echo "⏳ Second ping to $TARGET_URL (08:50 JST)..."
          curl -fsS --max-time 10 "$TARGET_URL" || echo "⚠️ Second ping failed"

      - name: Complete
        run: |
          echo "✅ Morning cron pings completed"
